version: '3'

services:
  flaskapp:
    build: ./flask_app
    container_name: app
#    ports:
#      - '8000:8000'
    network_mode: bridge
    networks:
      - first

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=3.250.41.107
    restart: always
    ports:
      - '80:80'
    network_mode: bridge
    networks:
      - first

networks:
  first:

