version: '3'

services:
  flaskapp:
    build: ./flask_app
    container_name: app
#    networks:
#      - first

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=3.250.41.107
    restart: always
    ports:
      - '80:80'
#    networks:
#      - first
#
#networks:
#  first:

