version: '3'

services:
  flaskapp:
    build: ./flask_app
    container_name: app
    ports:
      - '8000:8000'
    network_mode: bridge

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=34.241.34.97
    restart: always
    network_mode: bridge

